### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ProfNandaa** [dominicrodger/kanisa#74]
Great project Dominic!

Would love to contribute to the project, been thinking of a similar project but mainly more of RESTful app.

Writing from Nairobi. I attend [Parklands Baptist](http://parklandsbaptist.org/) :)

**Comment by dominicrodger** [comment]
Thanks @ProfNandaa! I'd welcome contributions if you see anything you'd like to change/improve!

**Comment by ProfNandaa** [comment]
Sure, will do so @dominicrodger :-)
